In [44]:
from itertools import product, permutations, combinations
import numpy as np
locs = ["A","B","C","D"]
ages = ["young", "old"]

traits = {
    "loc": locs,
    "age": ages
}

strats = ["loc","age"]

# AB
# CD

In [98]:
all_comps = list(product(locs,ages))
all_comp_table = np.array(list(zip(*all_comps)))
ncomps = len(all_comps)

In [99]:
all_comp_table

array([['A', 'A', 'B', 'B', 'C', 'C', 'D', 'D'],
       ['young', 'old', 'young', 'old', 'young', 'old', 'young', 'old']],
      dtype='<U5')

In [100]:
class TransitionFlow:
    def __init__(self, flow_cat_pairs, base_flow):
        self.flow_cat_pairs = flow_cat_pairs
        self.src, self.dest = zip(*flow_cat_pairs)
        self.base_flow = base_flow

        self.adjustments = []

    def apply(self, comp_vals):
        pass
        # get all source compartment values in our native shape
        # iterate through adjustments; everything is naive and 'flat' in this impl

In [102]:
pop_movement = TransitionFlow(list(permutations([("loc", (l,)) for l in locs],2)), 0.01)

In [103]:
all_comp_table

array([['A', 'A', 'B', 'B', 'C', 'C', 'D', 'D'],
       ['young', 'old', 'young', 'old', 'young', 'old', 'young', 'old']],
      dtype='<U5')

In [106]:
np.arange(ncomps)[np.isin(all_comp_table[0],("A","B"))]

array([0, 1, 2, 3])

In [110]:
np.where(np.isin(all_comp_table[0],("A","B")))[0]

array([0, 1, 2, 3])

In [123]:
# identify all compartments involved and build src, dest tables
# identify which table indices are involved in the adjustment
# apply the adjustment to the flow array (whose indices are the above table)
# return the adjusted (whole flow) array, with index

def comps_involved(query):
    src_strat, src_trait_list = query
    strat_idx = strats.index(src_strat)
    comp_idx = np.where(np.isin(all_comp_table[strat_idx], src_trait_list))[0]
    return comp_idx

in_comps = []
out_comps = []
flow_idx = []

for source_query, dest_query in pop_movement.flow_cat_pairs:
    source_comps = comps_involved(source_query)
    dest_comps = comps_involved(dest_query)
    in_comps.append(source_comps)
    out_comps.append(dest_comps)

src_idx, dest_idx = np.concat(in_comps), np.concat(out_comps)

comp_vals = np.linspace(1.0,ncomps,ncomps)


comps_involved(("age",["young"]))

from jax import numpy as jnp

comp_vals = jnp.array(comp_vals)
        

In [126]:
src_idx

array([0, 1, 0, 1, 0, 1, 2, 3, 2, 3, 2, 3, 4, 5, 4, 5, 4, 5, 6, 7, 6, 7,
       6, 7])

In [125]:
comp_vals.at[src_idx]

_IndexUpdateRef(Array([1., 2., 3., 4., 5., 6., 7., 8.], dtype=float32), array([0, 1, 0, 1, 0, 1, 2, 3, 2, 3, 2, 3, 4, 5, 4, 5, 4, 5, 6, 7, 6, 7,
       6, 7]))

In [128]:
flow_vals = jnp.ones(len(src_idx))

comp_vals.at[src_idx].subtract(flow_vals)



Array([-2., -1.,  0.,  1.,  2.,  3.,  4.,  5.], dtype=float32)

In [76]:
set(pop_movement.src),set(pop_movement.dest)

({('loc', ('A',)), ('loc', ('B',)), ('loc', ('C',)), ('loc', ('D',))},
 {('loc', ('A',)), ('loc', ('B',)), ('loc', ('C',)), ('loc', ('D',))})

In [ ]:
("src", "loc", np.array((1.2,1.4,1.9)))

In [ ]:
class ScatterMul:
    def __init__(self, proportions):
        self.proportions = proportions

    def apply(self, )
        
class ScatterEqual:
    def __init__(self):
        pass

    def apply(self, )

In [ ]:
("loc","loc")


In [55]:
pop_movement.src

({'loc': ['A']},
 {'loc': ['A']},
 {'loc': ['A']},
 {'loc': ['B']},
 {'loc': ['B']},
 {'loc': ['B']},
 {'loc': ['C']},
 {'loc': ['C']},
 {'loc': ['C']},
 {'loc': ['D']},
 {'loc': ['D']},
 {'loc': ['D']})

In [57]:
src_loc = [{"loc": l} for l in locs]
src_loc

[{'loc': 'A'}, {'loc': 'B'}, {'loc': 'C'}, {'loc': 'D'}]

In [58]:
all_comps

[('A', 'young'),
 ('A', 'old'),
 ('B', 'young'),
 ('B', 'old'),
 ('C', 'young'),
 ('C', 'old'),
 ('D', 'young'),
 ('D', 'old')]

In [59]:
flow_vals_base = np.ones(len(pop_movement.flow_cat_pairs))

In [60]:
flow_vals_base

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
for cat_group in pop_movement.src:
    